name: detrash
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0
  email_validator: ^2.1.17
  intl_phone_field: ^3.1.0
  lottie: 2.0.0
  flutter_native_splash: 2.2.15
  persistent_bottom_nav_bar: 5.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
    - assets/lottie/
  uses-material-design: true

